# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/ec_group_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/ec_group_messages.proto',
  package='zeth_proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x61pi/ec_group_messages.proto\x12\nzeth_proto\"<\n\x18HexPointBaseGroup1Affine\x12\x0f\n\x07x_coord\x18\x01 \x01(\t\x12\x0f\n\x07y_coord\x18\x02 \x01(\t\"<\n\x18HexPointBaseGroup2Affine\x12\x0f\n\x07x_coord\x18\x01 \x03(\t\x12\x0f\n\x07y_coord\x18\x02 \x03(\tb\x06proto3')
)




_HEXPOINTBASEGROUP1AFFINE = _descriptor.Descriptor(
  name='HexPointBaseGroup1Affine',
  full_name='zeth_proto.HexPointBaseGroup1Affine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_coord', full_name='zeth_proto.HexPointBaseGroup1Affine.x_coord', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_coord', full_name='zeth_proto.HexPointBaseGroup1Affine.y_coord', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=103,
)


_HEXPOINTBASEGROUP2AFFINE = _descriptor.Descriptor(
  name='HexPointBaseGroup2Affine',
  full_name='zeth_proto.HexPointBaseGroup2Affine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_coord', full_name='zeth_proto.HexPointBaseGroup2Affine.x_coord', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_coord', full_name='zeth_proto.HexPointBaseGroup2Affine.y_coord', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['HexPointBaseGroup1Affine'] = _HEXPOINTBASEGROUP1AFFINE
DESCRIPTOR.message_types_by_name['HexPointBaseGroup2Affine'] = _HEXPOINTBASEGROUP2AFFINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HexPointBaseGroup1Affine = _reflection.GeneratedProtocolMessageType('HexPointBaseGroup1Affine', (_message.Message,), {
  'DESCRIPTOR' : _HEXPOINTBASEGROUP1AFFINE,
  '__module__' : 'api.ec_group_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.HexPointBaseGroup1Affine)
  })
_sym_db.RegisterMessage(HexPointBaseGroup1Affine)

HexPointBaseGroup2Affine = _reflection.GeneratedProtocolMessageType('HexPointBaseGroup2Affine', (_message.Message,), {
  'DESCRIPTOR' : _HEXPOINTBASEGROUP2AFFINE,
  '__module__' : 'api.ec_group_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.HexPointBaseGroup2Affine)
  })
_sym_db.RegisterMessage(HexPointBaseGroup2Affine)


# @@protoc_insertion_point(module_scope)
